### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by PanoramicPanda** [smp4903/TotalQuestXP#1]
Unsure where possible logs are but... the addon simply isn't working for Classic.

Sometimes I have a purple bar, sometimes I have a bar with an experience number that never changes or updates. Either way, not functional for me :(

**Comment by dalinqin** [comment]
ya,i i originally put much hope on this addon ,but it's showing nothing but an empty bar there.

**Comment by PanoramicPanda** [comment]
Seems to be working as of latest release.
